services:
  postgresql:
    container_name: imperia_pg_infra
    image: postgres:latest
    env_file:
      - path: "../../.env.local"
        required: true
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${DOCKER_DB_USER}
        POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
        POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - imperia-network
    restart: always
  dragonfly:
    container_name: imperia_dragonfly_infra
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data/dragonfly:/data
networks:
  imperia-network:
    driver: bridge
volumes:
  postgresqldata:
  dragonflydata: