services:
  postgresql:
    container_name: imperia_pg_infra
    image: postgres:latest
    env_file:
      - path: "../../.env"
        required: true
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${DOCKER_DB_USER}
        POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
        POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - imperia-network
    restart: always
  dragonfly:
    container_name: imperia_dragonfly_infra
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data/dragonfly:/data
    networks:
      - imperia-network
  # lavalink:
  #   container_name: imperia_lavalink_infra
  #   image: fredboat/lavalink:latest
  #   ports:
  #     - "2333:2333"
  #   volumes:
  #     - ./docker/infra/lavalink.yml:/opt/Lavalink/application.yml:ro
  #   networks:
  #     - imperia-network
networks:
  imperia-network:
    driver: bridge