services:
  dev-postgresql:
    container_name: imperia-pg
    image: postgres:latest
    env_file:
      - path: "../../.env"
        required: true
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${DOCKER_DB_USER}
        POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
        POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - imperia-network
    restart: always
networks:
  imperia-network:
    driver: bridge